/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStartpageRouteImport } from './routes/api/startpage'
import { Route as ApiIconNameRouteImport } from './routes/api/icon.$name'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartpageRoute = ApiStartpageRouteImport.update({
  id: '/api/startpage',
  path: '/api/startpage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconNameRoute = ApiIconNameRouteImport.update({
  id: '/api/icon/$name',
  path: '/api/icon/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/startpage': typeof ApiStartpageRoute
  '/api/icon/$name': typeof ApiIconNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/startpage': typeof ApiStartpageRoute
  '/api/icon/$name': typeof ApiIconNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/api/startpage': typeof ApiStartpageRoute
  '/api/icon/$name': typeof ApiIconNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/login' | '/setup' | '/api/startpage' | '/api/icon/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/login' | '/setup' | '/api/startpage' | '/api/icon/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/api/startpage'
    | '/api/icon/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiStartpageRoute: typeof ApiStartpageRoute
  ApiIconNameRoute: typeof ApiIconNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startpage': {
      id: '/api/startpage'
      path: '/api/startpage'
      fullPath: '/api/startpage'
      preLoaderRoute: typeof ApiStartpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icon/$name': {
      id: '/api/icon/$name'
      path: '/api/icon/$name'
      fullPath: '/api/icon/$name'
      preLoaderRoute: typeof ApiIconNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiStartpageRoute: ApiStartpageRoute,
  ApiIconNameRoute: ApiIconNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
